import { type User } from "../util/types.ts";

const users = new Map<number, User>([
  [
    25,
    {
      id: 25,
      email: "Clovis_Bradtke69@transneft.ru",
      isActive: true,
      firstName: "Malvina",
      lastName: "Feeney",
      middleName: "Cormier",
      registeredAt: new Date("4/18/2025, 5:25:26 AM"),
      userName: "Cortez8",
      isExcluded: false,
    },
  ],
  [
    84,
    {
      id: 84,
      email: "Helena_Ritchie90@transneft.ru",
      isActive: true,
      firstName: "Waldo",
      lastName: "Fisher",
      middleName: "Roob",
      registeredAt: new Date("4/18/2025, 1:45:35 AM"),
      userName: "Evert_Yundt13",
      isExcluded: false,
    },
  ],
  [
    59,
    {
      id: 59,
      email: "Eriberto.Thiel@transneft.ru",
      isActive: false,
      firstName: "Alivia",
      lastName: "Monahan",
      middleName: "Kub",
      registeredAt: new Date("4/18/2025, 7:59:14 AM"),
      userName: "Jeremie.Jerde61",
      isExcluded: false,
    },
  ],
  [
    62,
    {
      id: 62,
      email: "Federico85@transneft.ru",
      isActive: true,
      firstName: "Faye",
      lastName: "D'Amore",
      middleName: "Cummings",
      registeredAt: new Date("4/18/2025, 1:28:08 PM"),
      userName: "Lawrence67",
      isExcluded: false,
    },
  ],
  [
    43,
    {
      id: 43,
      email: "Jeromy_Wiegand@transneft.ru",
      isActive: true,
      firstName: "Colt",
      lastName: "Hills",
      middleName: "Jaskolski",
      registeredAt: new Date("4/18/2025, 5:15:52 AM"),
      userName: "Cielo5",
      isExcluded: false,
    },
  ],
  [
    22,
    {
      id: 22,
      email: "Rosella.Dare10@transneft.ru",
      isActive: false,
      firstName: "Golden",
      lastName: "Hegmann",
      middleName: "Tillman",
      registeredAt: new Date("4/17/2025, 5:21:04 PM"),
      userName: "Dovie_Koepp",
      isExcluded: false,
    },
  ],
  [
    3,
    {
      id: 3,
      email: "Fausto_White65@transneft.ru",
      isActive: false,
      firstName: "Halie",
      lastName: "Kutch",
      middleName: "Weimann",
      registeredAt: new Date("4/18/2025, 9:29:38 AM"),
      userName: "Molly78",
      isExcluded: false,
    },
  ],
  [
    82,
    {
      id: 82,
      email: "Maxie_Goodwin88@transneft.ru",
      isActive: true,
      firstName: "Nico",
      lastName: "Reichert",
      middleName: "Bradtke",
      registeredAt: new Date("4/18/2025, 5:13:59 AM"),
      userName: "Anahi_Cormier",
      isExcluded: false,
    },
  ],
  [
    51,
    {
      id: 51,
      email: "Bonnie_OConnell99@transneft.ru",
      isActive: true,
      firstName: "Amparo",
      lastName: "Renner",
      middleName: "Anderson",
      registeredAt: new Date("4/17/2025, 6:35:19 PM"),
      userName: "London.Spencer59",
      isExcluded: false,
    },
  ],
  [
    42,
    {
      id: 42,
      email: "Dewayne_Schneider18@transneft.ru",
      isActive: false,
      firstName: "Franco",
      lastName: "Grant",
      middleName: "Gutmann",
      registeredAt: new Date("4/17/2025, 9:08:13 PM"),
      userName: "Jacky92",
      isExcluded: false,
    },
  ],
  [
    47,
    {
      id: 47,
      email: "Marty.OConnell@transneft.ru",
      isActive: false,
      firstName: "Barbara",
      lastName: "Dickinson",
      middleName: "Pacocha",
      registeredAt: new Date("4/17/2025, 5:09:56 PM"),
      userName: "Odell_Schaden",
      isExcluded: false,
    },
  ],
  [
    66,
    {
      id: 66,
      email: "Vilma40@transneft.ru",
      isActive: true,
      firstName: "Stephan",
      lastName: "D'Amore",
      middleName: "Rath",
      registeredAt: new Date("4/18/2025, 7:14:15 AM"),
      userName: "Georgette3",
      isExcluded: false,
    },
  ],
  [
    8,
    {
      id: 8,
      email: "Feylord27@transneft.ru",
      isActive: true,
      firstName: "Maximillia",
      lastName: "Abernathy",
      middleName: "Romaguera",
      registeredAt: new Date("4/18/2025, 10:22:40 AM"),
      userName: "Florence_Kirlin",
      isExcluded: false,
    },
  ],
  [
    85,
    {
      id: 85,
      email: "Garnett40@transneft.ru",
      isActive: true,
      firstName: "Deontae",
      lastName: "Glover",
      middleName: "Heidenreich",
      registeredAt: new Date("4/18/2025, 3:13:19 PM"),
      userName: "Rylan15",
      isExcluded: false,
    },
  ],
  [
    60,
    {
      id: 60,
      email: "Angela_Waters@transneft.ru",
      isActive: true,
      firstName: "Austyn",
      lastName: "McDermott",
      middleName: "Ryan",
      registeredAt: new Date("4/18/2025, 11:37:52 AM"),
      userName: "Duncan_Wisozk",
      isExcluded: false,
    },
  ],
  [
    94,
    {
      id: 94,
      email: "Alice_Huels52@transneft.ru",
      isActive: false,
      firstName: "Sydnie",
      lastName: "McKenzie",
      middleName: "Donnelly",
      registeredAt: new Date("4/18/2025, 1:26:06 AM"),
      userName: "Randy14",
      isExcluded: false,
    },
  ],
  [
    54,
    {
      id: 54,
      email: "Lelia.Jacobi@transneft.ru",
      isActive: false,
      firstName: "Orlo",
      lastName: "Connelly",
      middleName: "Treutel",
      registeredAt: new Date("4/17/2025, 5:29:53 PM"),
      userName: "Janie64",
      isExcluded: false,
    },
  ],
  [
    98,
    {
      id: 98,
      email: "Keshaun_Hettinger90@transneft.ru",
      isActive: true,
      firstName: "Fredy",
      lastName: "Greenfelder",
      middleName: "Cormier",
      registeredAt: new Date("4/18/2025, 2:10:36 PM"),
      userName: "Kareem.Fahey",
      isExcluded: false,
    },
  ],
  [
    31,
    {
      id: 31,
      email: "Emmett_Funk65@transneft.ru",
      isActive: false,
      firstName: "Xzavier",
      lastName: "Block",
      middleName: "Hackett",
      registeredAt: new Date("4/18/2025, 4:40:48 AM"),
      userName: "Jackie_Dare",
      isExcluded: false,
    },
  ],
  [
    73,
    {
      id: 73,
      email: "Audra.Hodkiewicz6@transneft.ru",
      isActive: true,
      firstName: "Stan",
      lastName: "Murphy",
      middleName: "VonRueden",
      registeredAt: new Date("4/18/2025, 4:08:50 PM"),
      userName: "Zetta39",
      isExcluded: false,
    },
  ],
  [
    12,
    {
      id: 12,
      email: "Kristian35@transneft.ru",
      isActive: false,
      firstName: "Alene",
      lastName: "Bernhard",
      middleName: "Hilpert",
      registeredAt: new Date("4/18/2025, 2:33:35 PM"),
      userName: "Korbin48",
      isExcluded: false,
    },
  ],
  [
    9,
    {
      id: 9,
      email: "Baron98@transneft.ru",
      isActive: true,
      firstName: "Kiarra",
      lastName: "Macejkovic",
      middleName: "Keebler",
      registeredAt: new Date("4/18/2025, 3:40:42 PM"),
      userName: "Kane48",
      isExcluded: false,
    },
  ],
  [
    33,
    {
      id: 33,
      email: "Aglae.Hansen44@transneft.ru",
      isActive: true,
      firstName: "Willy",
      lastName: "Renner",
      middleName: "Nader",
      registeredAt: new Date("4/17/2025, 9:18:30 PM"),
      userName: "Abigail_Franecki96",
      isExcluded: false,
    },
  ],
  [
    90,
    {
      id: 90,
      email: "Eve.Sanford15@transneft.ru",
      isActive: false,
      firstName: "Madisen",
      lastName: "Grimes",
      middleName: "Kiehn",
      registeredAt: new Date("4/18/2025, 2:59:17 PM"),
      userName: "Bennett_Larson",
      isExcluded: false,
    },
  ],
  [
    53,
    {
      id: 53,
      email: "Marvin_Koch@transneft.ru",
      isActive: false,
      firstName: "Jazmyn",
      lastName: "Rippin",
      middleName: "Pollich",
      registeredAt: new Date("4/18/2025, 5:32:56 AM"),
      userName: "Marshall38",
      isExcluded: false,
    },
  ],
  [
    79,
    {
      id: 79,
      email: "Anne.Wyman@transneft.ru",
      isActive: true,
      firstName: "Toney",
      lastName: "Larkin",
      middleName: "Metz",
      registeredAt: new Date("4/18/2025, 10:53:26 AM"),
      userName: "Margarete66",
      isExcluded: false,
    },
  ],
  [
    7,
    {
      id: 7,
      email: "Horacio31@transneft.ru",
      isActive: false,
      firstName: "Percy",
      lastName: "Gleason",
      middleName: "Denesik",
      registeredAt: new Date("4/18/2025, 12:07:37 AM"),
      userName: "Rachel25",
      isExcluded: false,
    },
  ],
  [
    24,
    {
      id: 24,
      email: "Justina_Bernier@transneft.ru",
      isActive: false,
      firstName: "Ethan",
      lastName: "Reichel",
      middleName: "Hammes",
      registeredAt: new Date("4/18/2025, 6:30:30 AM"),
      userName: "Mohammed_Boyle",
      isExcluded: false,
    },
  ],
  [
    15,
    {
      id: 15,
      email: "Kacie92@transneft.ru",
      isActive: false,
      firstName: "Russell",
      lastName: "Bashirian",
      middleName: "Walker",
      registeredAt: new Date("4/18/2025, 8:55:11 AM"),
      userName: "Ryder88",
      isExcluded: false,
    },
  ],
  [
    21,
    {
      id: 21,
      email: "Mallie.Nitzsche88@transneft.ru",
      isActive: false,
      firstName: "Salma",
      lastName: "Roberts",
      middleName: "Rolfson",
      registeredAt: new Date("4/18/2025, 5:42:56 AM"),
      userName: "Pearl_Goldner13",
      isExcluded: false,
    },
  ],
  [
    26,
    {
      id: 26,
      email: "Eliza_Kemmer70@transneft.ru",
      isActive: true,
      firstName: "Amy",
      lastName: "Fahey",
      middleName: "O'Kon",
      registeredAt: new Date("4/17/2025, 6:06:24 PM"),
      userName: "Joy.Rosenbaum80",
      isExcluded: false,
    },
  ],
  [
    83,
    {
      id: 83,
      email: "Napoleon.Hintz58@transneft.ru",
      isActive: true,
      firstName: "Josh",
      lastName: "Farrell",
      middleName: "Gislason",
      registeredAt: new Date("4/18/2025, 3:47:18 AM"),
      userName: "Vita45",
      isExcluded: false,
    },
  ],
  [
    40,
    {
      id: 40,
      email: "Chase_Cummerata80@transneft.ru",
      isActive: false,
      firstName: "Morris",
      lastName: "Medhurst",
      middleName: "Glover",
      registeredAt: new Date("4/18/2025, 4:48:12 AM"),
      userName: "Archibald4",
      isExcluded: false,
    },
  ],
  [
    58,
    {
      id: 58,
      email: "Jaunita.Stracke83@transneft.ru",
      isActive: true,
      firstName: "Jovanny",
      lastName: "Jaskolski",
      middleName: "Dickens",
      registeredAt: new Date("4/18/2025, 10:08:01 AM"),
      userName: "Maymie_Mitchell",
      isExcluded: false,
    },
  ],
  [
    93,
    {
      id: 93,
      email: "Billie39@transneft.ru",
      isActive: true,
      firstName: "Eloise",
      lastName: "Hermann",
      middleName: "Schimmel",
      registeredAt: new Date("4/18/2025, 3:37:03 AM"),
      userName: "Marty_Skiles",
      isExcluded: false,
    },
  ],
  [
    87,
    {
      id: 87,
      email: "Golda.Sporer@transneft.ru",
      isActive: false,
      firstName: "Freddy",
      lastName: "Parisian",
      middleName: "Brekke",
      registeredAt: new Date("4/18/2025, 9:01:10 AM"),
      userName: "Helen_Upton",
      isExcluded: false,
    },
  ],
  [
    71,
    {
      id: 71,
      email: "Virginie77@transneft.ru",
      isActive: true,
      firstName: "Clementine",
      lastName: "Schmeler",
      middleName: "Fahey",
      registeredAt: new Date("4/18/2025, 5:11:05 AM"),
      userName: "Tommie.Bradtke87",
      isExcluded: false,
    },
  ],
  [
    50,
    {
      id: 50,
      email: "Kamryn.Stiedemann24@transneft.ru",
      isActive: true,
      firstName: "Jeremie",
      lastName: "Bogisich",
      middleName: "Prohaska",
      registeredAt: new Date("4/18/2025, 11:23:29 AM"),
      userName: "Tyra.Batz39",
      isExcluded: false,
    },
  ],
  [
    6,
    {
      id: 6,
      email: "Ole.Padberg1@transneft.ru",
      isActive: false,
      firstName: "Benton",
      lastName: "Stracke",
      middleName: "Weber",
      registeredAt: new Date("4/18/2025, 8:45:36 AM"),
      userName: "Armando.Ziemann",
      isExcluded: false,
    },
  ],
  [
    28,
    {
      id: 28,
      email: "Malika21@transneft.ru",
      isActive: true,
      firstName: "Mark",
      lastName: "Tromp",
      middleName: "Gleichner",
      registeredAt: new Date("4/17/2025, 10:05:14 PM"),
      userName: "Matteo58",
      isExcluded: false,
    },
  ],
  [
    61,
    {
      id: 61,
      email: "Kelley55@transneft.ru",
      isActive: false,
      firstName: "Lilian",
      lastName: "Witting",
      middleName: "Raynor",
      registeredAt: new Date("4/18/2025, 1:09:19 PM"),
      userName: "Deja41",
      isExcluded: false,
    },
  ],
  [
    69,
    {
      id: 69,
      email: "Thea_Schaden@transneft.ru",
      isActive: true,
      firstName: "Deven",
      lastName: "Erdman",
      middleName: "Simonis",
      registeredAt: new Date("4/18/2025, 3:36:27 AM"),
      userName: "Mckenzie27",
      isExcluded: false,
    },
  ],
  [
    32,
    {
      id: 32,
      email: "Norbert66@transneft.ru",
      isActive: true,
      firstName: "Vella",
      lastName: "Casper",
      middleName: "Gorczany",
      registeredAt: new Date("4/18/2025, 11:14:38 AM"),
      userName: "Lilly.Pfannerstill87",
      isExcluded: false,
    },
  ],
  [
    44,
    {
      id: 44,
      email: "Elva.Ortiz27@transneft.ru",
      isActive: true,
      firstName: "Beverly",
      lastName: "Kertzmann",
      middleName: "McLaughlin",
      registeredAt: new Date("4/18/2025, 2:31:22 PM"),
      userName: "Celia_Sanford",
      isExcluded: false,
    },
  ],
  [
    45,
    {
      id: 45,
      email: "Willa_Altenwerth@transneft.ru",
      isActive: true,
      firstName: "Ayden",
      lastName: "Kuhn",
      middleName: "Koch",
      registeredAt: new Date("4/18/2025, 3:10:47 PM"),
      userName: "Pearline69",
      isExcluded: false,
    },
  ],
  [
    38,
    {
      id: 38,
      email: "Makenzie_Ebert15@transneft.ru",
      isActive: true,
      firstName: "Lue",
      lastName: "Marks",
      middleName: "Prosacco",
      registeredAt: new Date("4/18/2025, 8:37:35 AM"),
      userName: "Adrienne16",
      isExcluded: false,
    },
  ],
  [
    30,
    {
      id: 30,
      email: "Patricia65@transneft.ru",
      isActive: false,
      firstName: "Timmothy",
      lastName: "Howe",
      middleName: "Prosacco",
      registeredAt: new Date("4/17/2025, 4:19:43 PM"),
      userName: "Clara.Yost",
      isExcluded: false,
    },
  ],
  [
    86,
    {
      id: 86,
      email: "Leonel61@transneft.ru",
      isActive: false,
      firstName: "Rowena",
      lastName: "O'Keefe",
      middleName: "Pagac",
      registeredAt: new Date("4/17/2025, 11:29:35 PM"),
      userName: "Dora60",
      isExcluded: false,
    },
  ],
  [
    46,
    {
      id: 46,
      email: "Houston_Feil57@transneft.ru",
      isActive: true,
      firstName: "Toby",
      lastName: "Carroll",
      middleName: "Kerluke",
      registeredAt: new Date("4/18/2025, 12:23:25 PM"),
      userName: "Amir_Monahan",
      isExcluded: false,
    },
  ],
  [
    67,
    {
      id: 67,
      email: "Natalie.Thompson20@transneft.ru",
      isActive: false,
      firstName: "Obie",
      lastName: "Durgan",
      middleName: "McKenzie",
      registeredAt: new Date("4/18/2025, 1:50:17 AM"),
      userName: "Adolphus_Schumm2",
      isExcluded: false,
    },
  ],
  [
    41,
    {
      id: 41,
      email: "Columbus_Ledner@transneft.ru",
      isActive: false,
      firstName: "Rollin",
      lastName: "Okuneva",
      middleName: "Ziemann",
      registeredAt: new Date("4/18/2025, 4:10:11 PM"),
      userName: "Tobin_Kunze",
      isExcluded: false,
    },
  ],
  [
    34,
    {
      id: 34,
      email: "Cali_Abbott@transneft.ru",
      isActive: false,
      firstName: "Emmy",
      lastName: "Trantow",
      middleName: "Cummings",
      registeredAt: new Date("4/18/2025, 11:57:53 AM"),
      userName: "Ardith_Dickens",
      isExcluded: false,
    },
  ],
  [
    18,
    {
      id: 18,
      email: "Abdul.Nikolaus@transneft.ru",
      isActive: true,
      firstName: "Alfred",
      lastName: "Spinka",
      middleName: "Hahn",
      registeredAt: new Date("4/18/2025, 6:24:52 AM"),
      userName: "Jabari5",
      isExcluded: false,
    },
  ],
  [
    72,
    {
      id: 72,
      email: "Jerod4@transneft.ru",
      isActive: false,
      firstName: "Gabrielle",
      lastName: "Hermann",
      middleName: "Reichel",
      registeredAt: new Date("4/17/2025, 5:28:04 PM"),
      userName: "Emil_Von49",
      isExcluded: false,
    },
  ],
  [
    92,
    {
      id: 92,
      email: "Zoila.Haag@transneft.ru",
      isActive: true,
      firstName: "Eleazar",
      lastName: "Hermiston",
      middleName: "Gutmann",
      registeredAt: new Date("4/18/2025, 7:33:34 AM"),
      userName: "Kassandra_Spinka",
      isExcluded: false,
    },
  ],
  [
    36,
    {
      id: 36,
      email: "Gilda72@transneft.ru",
      isActive: true,
      firstName: "Brandi",
      lastName: "Heidenreich",
      middleName: "Johns",
      registeredAt: new Date("4/18/2025, 5:08:09 AM"),
      userName: "Rowena_Kassulke97",
      isExcluded: false,
    },
  ],
  [
    48,
    {
      id: 48,
      email: "Ardith37@transneft.ru",
      isActive: false,
      firstName: "Westley",
      lastName: "Bayer",
      middleName: "Nitzsche",
      registeredAt: new Date("4/18/2025, 4:06:09 AM"),
      userName: "Tremaine_Kreiger90",
      isExcluded: false,
    },
  ],
  [
    35,
    {
      id: 35,
      email: "Taryn.Rice95@transneft.ru",
      isActive: true,
      firstName: "Dashawn",
      lastName: "Leuschke",
      middleName: "Medhurst",
      registeredAt: new Date("4/18/2025, 8:49:20 AM"),
      userName: "Josie_Gerhold",
      isExcluded: false,
    },
  ],
  [
    55,
    {
      id: 55,
      email: "Candido.Schultz72@transneft.ru",
      isActive: true,
      firstName: "Kristy",
      lastName: "Powlowski",
      middleName: "Feeney",
      registeredAt: new Date("4/18/2025, 9:51:59 AM"),
      userName: "Ola.Hoppe80",
      isExcluded: false,
    },
  ],
  [
    96,
    {
      id: 96,
      email: "Rusty.Kuphal@transneft.ru",
      isActive: true,
      firstName: "Marisol",
      lastName: "Beahan",
      middleName: "Ullrich",
      registeredAt: new Date("4/18/2025, 2:37:43 AM"),
      userName: "Alek71",
      isExcluded: false,
    },
  ],
  [
    56,
    {
      id: 56,
      email: "Maddison_Monahan@transneft.ru",
      isActive: false,
      firstName: "Hallie",
      lastName: "Schultz",
      middleName: "Mann",
      registeredAt: new Date("4/18/2025, 1:51:35 AM"),
      userName: "Adell62",
      isExcluded: false,
    },
  ],
  [
    81,
    {
      id: 81,
      email: "Lera13@transneft.ru",
      isActive: false,
      firstName: "Santos",
      lastName: "Kerluke",
      middleName: "Leannon",
      registeredAt: new Date("4/18/2025, 6:12:19 AM"),
      userName: "Burley72",
      isExcluded: false,
    },
  ],
  [
    17,
    {
      id: 17,
      email: "Halie18@transneft.ru",
      isActive: true,
      firstName: "Maximo",
      lastName: "Jones",
      middleName: "Morar",
      registeredAt: new Date("4/18/2025, 9:25:39 AM"),
      userName: "Rebeka49",
      isExcluded: false,
    },
  ],
  [
    88,
    {
      id: 88,
      email: "Lafayette_Lind@transneft.ru",
      isActive: false,
      firstName: "Ena",
      lastName: "Schimmel",
      middleName: "Jakubowski",
      registeredAt: new Date("4/18/2025, 8:06:17 AM"),
      userName: "Grover_OKeefe16",
      isExcluded: false,
    },
  ],
  [
    68,
    {
      id: 68,
      email: "Erick_Fahey@transneft.ru",
      isActive: true,
      firstName: "Dennis",
      lastName: "Labadie",
      middleName: "Hackett",
      registeredAt: new Date("4/17/2025, 4:54:24 PM"),
      userName: "Owen.Balistreri35",
      isExcluded: false,
    },
  ],
  [
    78,
    {
      id: 78,
      email: "Lea.Deckow41@transneft.ru",
      isActive: false,
      firstName: "Montana",
      lastName: "Turner",
      middleName: "Hermiston",
      registeredAt: new Date("4/18/2025, 3:05:58 PM"),
      userName: "Matteo.Kohler97",
      isExcluded: false,
    },
  ],
]);

export default users;
